# Project: Login ID with Integrity Check
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o login.o security.o
LINKOBJ  = main.o login.o security.o
LIBS     = -L"C:/Users/201812358/C++17/mingw64/lib" -L"C:/Users/201812358/C++17/mingw64/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc -std=c++17
INCS     = -I"C:/Users/201812358/C++17/mingw64/include" -I"C:/Users/201812358/C++17/mingw64/x86_64-w64-mingw32/include" -I"C:/Users/201812358/C++17/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include"
CXXINCS  = -I"C:/Users/201812358/C++17/mingw64/include" -I"C:/Users/201812358/C++17/mingw64/x86_64-w64-mingw32/include" -I"C:/Users/201812358/C++17/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"C:/Users/201812358/C++17/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++"
BIN      = "Login ID with Integrity Check.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

login.o: login.cpp
	$(CPP) -c login.cpp -o login.o $(CXXFLAGS)

security.o: security.cpp
	$(CPP) -c security.cpp -o security.o $(CXXFLAGS)
